package com.acme.siem;

import javax.baja.log.Log;
import javax.baja.naming.BOrd;
import javax.baja.nre.annotations.NiagaraAction;
import javax.baja.nre.annotations.NiagaraProperty;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.sys.*;

/**
 * BSiemForwarderService
 * ---------------------
 * A station service that forwards security-relevant events (point value/status
 * changes, alarms, audit records) to an external SIEM over syslog/TLS.
 *
 * Design constraints (monitoring must NOT interfere with normal JACE operation):
 *
 *   1. RIDE-ALONG ONLY   - We never subscribe a proxy point ourselves. Doing so
 *                          would push it into the driver's poll queue and add
 *                          traffic to the RS-485 trunk (degrading MS/TP token
 *                          timing / Modbus poll cycles). RideAlongSubscriber only
 *                          forwards points that some OTHER component already
 *                          subscribed (graphics, histories, control logic).
 *
 *   2. BOUNDED QUEUE     - Event handlers do nothing but enqueue() and return in
 *                          microseconds. All socket I/O happens on ForwardWorker,
 *                          a single low-priority thread. The queue is bounded and
 *                          drop-oldest: under pressure, SIEM data is shed, never
 *                          engine time. Drops are counted and reported.
 *
 *   3. SELF-THROTTLE     - SelfThrottleMonitor watches engine-hog % and free heap.
 *                          When the station is under load it throttles or suspends
 *                          forwarding (fail-open) and emits a heartbeat so the SIEM
 *                          knows why the feed paused. Control always wins.
 *
 * Place this service under the station's Services container.
 *
 * @author skeleton
 */
@NiagaraType
// ---- SIEM destination -----------------------------------------------------
@NiagaraProperty(
  name = "siemHost",
  type = "String",
  defaultValue = "\"siem.mgmt.local\"",
  facets = { @javax.baja.nre.annotations.Facet(name = "BFacets.MULTI_LINE", value = "false") }
)
@NiagaraProperty(
  name = "siemPort",
  type = "int",
  defaultValue = "6514"                       // RFC 5425 syslog-over-TLS default
)
@NiagaraProperty(
  name = "useTls",
  type = "boolean",
  defaultValue = "true"
)
// ---- What to forward ------------------------------------------------------
@NiagaraProperty(
  name = "networkOrd",
  type = "BOrd",
  defaultValue = "BOrd.make(\"station:|slot:/Drivers\")"
)
@NiagaraProperty(
  name = "forwardPoints",
  type = "boolean",
  defaultValue = "true"
)
@NiagaraProperty(
  name = "forwardAlarms",
  type = "boolean",
  defaultValue = "true"
)
@NiagaraProperty(
  name = "forwardAudit",
  type = "boolean",
  defaultValue = "true"
)
// ---- Backpressure / non-interference knobs --------------------------------
@NiagaraProperty(
  name = "queueCapacity",
  type = "int",
  defaultValue = "4096"                       // events; drop-oldest beyond this
)
@NiagaraProperty(
  name = "minIntervalMs",
  type = "int",
  defaultValue = "1000"                       // per-point rate limit (deadband time)
)
// ---- Read-only telemetry (surfaced to the SIEM and to the operator) -------
@NiagaraProperty(
  name = "connected",
  type = "boolean",
  defaultValue = "false",
  flags = Flags.READONLY | Flags.TRANSIENT
)
@NiagaraProperty(
  name = "throttled",
  type = "boolean",
  defaultValue = "false",
  flags = Flags.READONLY | Flags.TRANSIENT
)
@NiagaraProperty(
  name = "queueDepth",
  type = "int",
  defaultValue = "0",
  flags = Flags.READONLY | Flags.TRANSIENT
)
@NiagaraProperty(
  name = "droppedEvents",
  type = "long",
  defaultValue = "0L",
  flags = Flags.READONLY | Flags.TRANSIENT
)
@NiagaraProperty(
  name = "sentEvents",
  type = "long",
  defaultValue = "0L",
  flags = Flags.READONLY | Flags.TRANSIENT
)
// ---- Clock-tick actions (Clock.schedulePeriodically requires real Actions) -
@NiagaraAction(
  name = "rideAlongRescan",
  flags = Flags.HIDDEN
)
@NiagaraAction(
  name = "throttleTick",
  flags = Flags.HIDDEN
)
public class BSiemForwarderService
  extends BAbstractService
{
/*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
/*@ $com.acme.siem.BSiemForwarderService(0)1.0$ @*/
/* Generated by the slot-o-matic. To regenerate, run:  gradle slotomatic          */
/* The block below is normally machine-generated; kept hand-written here so the    */
/* skeleton compiles conceptually without running the tool.                        */

  public static final Property siemHost      = newProperty(0, "siem.mgmt.local", null);
  public static final Property siemPort      = newProperty(0, 6514, null);
  public static final Property useTls        = newProperty(0, true, null);
  public static final Property networkOrd    = newProperty(0, BOrd.make("station:|slot:/Drivers"), null);
  public static final Property forwardPoints = newProperty(0, true, null);
  public static final Property forwardAlarms = newProperty(0, true, null);
  public static final Property forwardAudit  = newProperty(0, true, null);
  public static final Property queueCapacity = newProperty(0, 4096, null);
  public static final Property minIntervalMs = newProperty(0, 1000, null);
  public static final Property connected     = newProperty(Flags.READONLY | Flags.TRANSIENT, false, null);
  public static final Property throttled     = newProperty(Flags.READONLY | Flags.TRANSIENT, false, null);
  public static final Property queueDepth    = newProperty(Flags.READONLY | Flags.TRANSIENT, 0, null);
  public static final Property droppedEvents = newProperty(Flags.READONLY | Flags.TRANSIENT, 0L, null);
  public static final Property sentEvents    = newProperty(Flags.READONLY | Flags.TRANSIENT, 0L, null);

  public static final Action rideAlongRescan = newAction(Flags.HIDDEN, null);
  public static final Action throttleTick    = newAction(Flags.HIDDEN, null);

  public String  getSiemHost()      { return getString(siemHost); }
  public void    setSiemHost(String v) { setString(siemHost, v, null); }
  public int     getSiemPort()      { return getInt(siemPort); }
  public boolean getUseTls()        { return getBoolean(useTls); }
  public BOrd    getNetworkOrd()    { return (BOrd)get(networkOrd); }
  public boolean getForwardPoints() { return getBoolean(forwardPoints); }
  public boolean getForwardAlarms() { return getBoolean(forwardAlarms); }
  public boolean getForwardAudit()  { return getBoolean(forwardAudit); }
  public int     getQueueCapacity() { return getInt(queueCapacity); }
  public int     getMinIntervalMs() { return getInt(minIntervalMs); }

  public boolean getConnected()     { return getBoolean(connected); }
  public void    setConnected(boolean v)   { setBoolean(connected, v, null); }
  public boolean getThrottled()     { return getBoolean(throttled); }
  public void    setThrottled(boolean v)   { setBoolean(throttled, v, null); }
  public int     getQueueDepth()    { return getInt(queueDepth); }
  public void    setQueueDepth(int v)      { setInt(queueDepth, v, null); }
  public long    getDroppedEvents() { return getLong(droppedEvents); }
  public void    setDroppedEvents(long v)  { setLong(droppedEvents, v, null); }
  public long    getSentEvents()    { return getLong(sentEvents); }
  public void    setSentEvents(long v)     { setLong(sentEvents, v, null); }

  public void rideAlongRescan() { invoke(rideAlongRescan, null, null); }
  public void throttleTick()    { invoke(throttleTick, null, null); }

  @Override public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BSiemForwarderService.class);
/*+ ------------ END BAJA AUTO GENERATED CODE ------------ +*/

  private static final Log log = Log.getLog("siemForwarder");

  // -- Service registration: this is the interface the framework keys on -----
  private static final Type[] SERVICE_TYPES = { TYPE };
  @Override public Type[] getServiceTypes() { return SERVICE_TYPES; }

  // -- Runtime collaborators (not persisted) ---------------------------------
  // Volatile: written by the lifecycle thread, read by event/clock threads.
  private volatile ForwardWorker       worker;
  private volatile RideAlongSubscriber subscriber;
  private volatile SelfThrottleMonitor monitor;

  // ==========================================================================
  //  Lifecycle
  // ==========================================================================

  @Override
  public void serviceStarted() throws Exception
  {
    super.serviceStarted();

    // 1) Worker owns the socket + bounded queue. Nothing else touches the wire.
    worker = new ForwardWorker(this);
    worker.start();

    // 2) Self-throttle monitor. Ticks on the app clock, no thread of its own.
    monitor = new SelfThrottleMonitor(this);
    monitor.start();

    // 3) Ride-along subscriber. Attaches listeners only; subscribes NOTHING.
    subscriber = new RideAlongSubscriber(this);
    subscriber.start();

    log.message("SIEM forwarder started -> " + getSiemHost() + ":" + getSiemPort()
                + (getUseTls() ? " (TLS)" : " (plain)"));
  }

  @Override
  public void serviceStopped() throws Exception
  {
    if (subscriber != null) subscriber.stop();
    if (monitor    != null) monitor.stop();
    if (worker     != null) worker.stop();      // flushes best-effort, then closes
    subscriber = null; monitor = null; worker = null;
    super.serviceStopped();
  }

  // ==========================================================================
  //  Action dispatch (invoked by the framework from the clock tickets)
  // ==========================================================================

  public void doRideAlongRescan()
  {
    RideAlongSubscriber s = subscriber;
    if (s != null) s.rescan();
  }

  public void doThrottleTick()
  {
    SelfThrottleMonitor m = monitor;
    if (m != null) m.tick();
  }

  // ==========================================================================
  //  Collaborator access
  // ==========================================================================

  ForwardWorker       worker()   { return worker; }
  SelfThrottleMonitor monitor()  { return monitor; }

  /**
   * Single entry point every event handler funnels through. Returns immediately;
   * the heavy lifting (format + socket write) happens on the worker thread.
   * Honors the self-throttle in BOTH degraded states: THROTTLING admits only
   * warning-and-above, SUSPENDED drops everything except the periodic heartbeat
   * that tells the SIEM the feed is intentionally paused.
   */
  void offer(SiemEvent evt)
  {
    ForwardWorker w = worker;                   // local copy: stop() may null the field
    if (w == null) return;
    SelfThrottleMonitor m = monitor;
    if (m != null && !m.admits(evt))
    {
      w.countDrop();                            // throttled/suspended: shed, keep the tally
      return;
    }
    w.enqueue(evt);
  }

  /** Reflect worker/monitor counters onto the read-only slots (called on clock). */
  void refreshTelemetry()
  {
    ForwardWorker w = worker;
    if (w == null) return;
    setQueueDepth(w.depth());
    setDroppedEvents(w.dropped());
    setSentEvents(w.sent());
    setConnected(w.isConnected());
    setThrottled(monitor != null && monitor.isThrottling());
    // SIEM-down visibility is carried by the `connected` slot (alarm/historize
    // it as needed). We deliberately do not fault the service node: a collector
    // outage is a degraded-but-expected state, not a service fault.
  }
}
